### ISSUE TITLE
Button does not show for Quest 81502

### ISSUE THREAD

**Issue by Gnarfoz** [p3lim-wow/ExtraQuestButton#96]
**Describe the bug**
The ExtraQuestButton does not show up for [this quest with a usable item](https://www.wowhead.com/quest=81502/testing-formulae-malodorous-philter).

**How to reproduce**
Obtain the quest.

**What did you expect?**
I expected the button to show up.

**Error report**
-

**Screenshots**
-

**Comment by p3lim** [comment]
After they added the interaction system with quest items I kind of stopped adding items that would exclusively interact with npcs/objects because that system just did it better, and is one of the reasons why items such as this one has not been added to the database. I've been looking for an API to get the information that the interact key uses, but I haven't found any.

I can just add this one, but there doesn't seem to be too much of an incentive to do so when right-clicking the correct mob does the same.

**Comment by Gnarfoz** [comment]
Interaction system? Are you saying pressing the interact keybind should use the quest item in this particular case?
Having a button I can bind to a key on my keyboard is the main advantage over having to find the mob in the 3D world and clicking on it...

**Comment by p3lim** [comment]
> Are you saying pressing the interact keybind should use the quest item in this particular case?

Yes, or just right-clicking the NPC/object. When close enough the cursor changes too:
![image](https://github.com/user-attachments/assets/328e1849-5df9-4440-a72b-ca18203e5f88)

You can bind this interaction if you want to:
![image](https://github.com/user-attachments/assets/324f75d7-5725-4fac-af9a-9afcd8a188a9)

EQB is still useful for quest items that don't require a target, which I'd say is about 30-40% of all quest items.

Ever since they added this system I've been using the interact key for pretty much anything, using quest items, talking to NPCs, opening doors, looting, fishing, you name it, just because it's a convenient key that works for all of it and doesn't require mouse movement (it's particularly useful for tiny objects). Because it works so well I've been slacking hard with adding quest items to the database that are intended for targets, as the interact system just works so well.
